version: '3.7'

services:
  flask-app:
    container_name: flask-app
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      - solr
    depends_on:
      - solr-filter

  solr-filter:
    image: solr:8.5
    container_name: solr-filter
    ports:
      - 8984:8983
    networks:
      - solr
    volumes: 
      - ./config:/var/solr/data/core-config
    entrypoint:
      - solr-precreate
      - vgsales
      - /var/solr/data/core-config

networks:
  solr:
