version: '3.7'

services:
  flask-app:
    container_name: flask-app
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      - solr
    depends_on:
      - solr

  solr-filter:
    image: solr:8.5
    container_name: solr-filter
    ports:
      - 8984:8983
    networks:
      - solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core vgsales; exec solr -f"

networks:
  solr:
