version: '3.7'

services:
  flask-app:
    container_name: flask-app
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - solr
    depends_on:
      - solr

  solr:
    image: solr:8.5
    container_name: solr
    ports:
      - "8983:8983"
    networks:
      - solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core vgsales; exec solr -f"

networks:
  solr:
